name: Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: CameraHackTool

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9'

    - name: Get version
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version
      with:
        proj-path: CameraHackTool/CameraHackTool.csproj

    - name: Build with dotnet
      working-directory: ./CameraHackTool
      run: |
        dotnet publish -c Release

    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CameraHackTool
        path: CameraHackTool\bin\Release\net9.0-windows\win-x64\publish\CameraHackTool.exe
        if-no-files-found: error
        retention-days: 7

    - name: Create and upload release
      id: create-new-release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get-version.outputs.version }}
        name: Release ${{ steps.get-version.outputs.version }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false
        files: ./CameraHackTool/bin/Release/net9.0-windows/win-x64/publish/CameraHackTool.exe